# Generated by Django 5.0.7 on 2026-01-04 22:47

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Church",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the church tenant",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the church", max_length=255
                    ),
                ),
                (
                    "church_code",
                    models.CharField(
                        help_text="Unique human-readable code for the church (can be rotated)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this church was created in the system",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this church record was last updated",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this church tenant is active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Church",
                "verbose_name_plural": "Churches",
                "db_table": "tenants_church",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["church_code"], name="tenants_chu_church__1e57f8_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="tenants_chu_is_acti_1b0959_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="tenants_chu_created_631751_idx"
                    ),
                ],
            },
        ),
    ]
