# Generated by Django 5.0.7 on 2026-01-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="church",
            name="login_cover_image",
            field=models.CharField(
                blank=True,
                help_text="S3 path to login page cover image (e.g., tenants/{church_id}/branding/cover.jpg)",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="church",
            name="logo_url",
            field=models.CharField(
                blank=True,
                help_text="S3 path to church logo (e.g., tenants/{church_id}/branding/logo.png)",
                max_length=500,
            ),
        ),
    ]
