# Generated by Django 5.0.7 on 2026-01-04 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="church",
            field=models.ForeignKey(
                blank=True,
                help_text="Church this user belongs to for tenant isolation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="tenants.church",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["church", "role"], name="core_user_church__05f000_idx"
            ),
        ),
    ]
