# Generated by Django 5.0.7 on 2026-01-04 23:20

import core.tenant_isolation
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_church_user_core_user_church__05f000_idx"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Album title (e.g., 'Easter Service 2026')",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of the album contents",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Whether album is visible to all church members",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Whether to feature this album prominently",
                    ),
                ),
                (
                    "event_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of the event this album represents",
                        null=True,
                    ),
                ),
                (
                    "church",
                    models.ForeignKey(
                        help_text="Church that owns this album",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="albums",
                        to="tenants.church",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this album",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_albums",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Album",
                "verbose_name_plural": "Albums",
                "ordering": ["-created_at"],
            },
            bases=(core.tenant_isolation.TenantScopedQuerySetMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Photo title or caption", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional photo description"
                    ),
                ),
                (
                    "filename",
                    models.CharField(help_text="Original filename", max_length=255),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        default="image/jpeg",
                        help_text="MIME type of the photo",
                        max_length=100,
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        blank=True, help_text="Image width in pixels", null=True
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        blank=True, help_text="Image height in pixels", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Whether photo is visible to all church members",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Whether to feature this photo prominently",
                    ),
                ),
                (
                    "taken_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the photo was taken (from EXIF data)",
                        null=True,
                    ),
                ),
                (
                    "camera_model",
                    models.CharField(
                        blank=True,
                        help_text="Camera model (from EXIF data)",
                        max_length=100,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Location where photo was taken",
                        max_length=200,
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        blank=True,
                        help_text="Album this photo belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="core.album",
                    ),
                ),
                (
                    "church",
                    models.ForeignKey(
                        help_text="Church that owns this photo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="tenants.church",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        help_text="User who uploaded this photo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_photos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Photo",
                "verbose_name_plural": "Photos",
                "ordering": ["-created_at"],
            },
            bases=(core.tenant_isolation.TenantScopedQuerySetMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name="album",
            index=models.Index(
                fields=["church", "created_at"], name="core_album_church__a7979c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="album",
            index=models.Index(
                fields=["church", "is_public"], name="core_album_church__c1d84b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="album",
            index=models.Index(
                fields=["church", "is_featured"], name="core_album_church__a489eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="album",
            index=models.Index(
                fields=["church", "event_date"], name="core_album_church__48ef80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="album",
            index=models.Index(
                fields=["created_by"], name="core_album_created_c0d58f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="album",
            unique_together={("church", "title")},
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                fields=["church", "created_at"], name="core_photo_church__a95f5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                fields=["church", "album"], name="core_photo_church__5b5931_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                fields=["church", "is_public"], name="core_photo_church__51140f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                fields=["church", "is_featured"], name="core_photo_church__d2f13e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                fields=["church", "taken_at"], name="core_photo_church__37868a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                fields=["album", "created_at"], name="core_photo_album_i_eee557_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                fields=["uploaded_by"], name="core_photo_uploade_c8e4b2_idx"
            ),
        ),
    ]
