# Generated by Django 5.0.7 on 2026-01-04 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_album_photo_album_core_album_church__a7979c_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="s3_key",
            field=models.CharField(
                blank=True,
                help_text="S3 object key for secure file access",
                max_length=500,
            ),
        ),
    ]
