# Generated by Django 5.0.7 on 2026-01-06 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_photo_s3_key"),
        ("tenants", "0002_church_login_cover_image_church_logo_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="church",
            field=models.ForeignKey(
                blank=True,
                help_text="Church this user belongs to for tenant isolation (null for superadmin)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="tenants.church",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "Super Admin"),
                    ("admin", "Admin"),
                    ("member", "Member"),
                ],
                default="member",
                help_text="User's role: superadmin (platform), admin (church), or member (church)",
                max_length=15,
            ),
        ),
    ]
